# Generated by Django 5.1.5 on 2025-01-28 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_question_priority'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
